name: Java Spring Test Workflow

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  spring-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Java environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # OpenJDK distribution
          java-version: '17'

      # 3. Install Gradle (if using Gradle)
      - name: Install Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-7.6-bin.zip
          unzip gradle-7.6-bin.zip
          export PATH=$PATH:$PWD/gradle-7.6/bin

      # 4. Run tests
      - name: Run Spring Tests
        run: |
          cd backend  # 자바 스프링 프로젝트 디렉토리로 이동
          ./gradlew test  # Gradle 사용 시
          # mvn test      # Maven 사용 시 (주석 해제 후 필요 시 대체)
