name: Backend Test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # OpenJDK distribution
          java-version: '17'

      # 3. Navigate to backend directory
      - name: Navigate to backend directory
        working-directory: backend/Travel
        run: |
          chmod +x ./gradlew # Grant execute permission
          ./gradlew test # Run tests with Gradle
